version: "2"
services:
  frontend:
    build: frontend
    ports:
      - "3000:3000"
  backend:
    build: backend
    ports:
      - "8080:8080"
    links:
      - mongodb
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - 27017:27017
